services:
  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - "8500:8500"
      - "2379:2379"
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
